kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker:linux-arm64
  settings:
    repo: h3rj4n/registry-manager
    dockerfile: Dockerfile.arm64v8
    tags:
      - latest
      - '3.0.3'
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
